### ISSUE TITLE
Provide versioned docker images

### ISSUE THREAD

**Issue by mr-karan** [lmangani/cLoki#68]
Hi

Firstly, thanks for building and open sourcing this project! It's super amazing and I came here after watching [this talk](https://www.youtube.com/watch?v=E1yuPXNz5Fo). Clickhouse fan here as well and would love to try this project in my org.

I am looking to set this up in production and aiming at a `docker` setup. I think it'll be really nice if the [docker images](https://hub.docker.com/r/qxip/cloki/tags) are published with proper tags and not `:latest`. Since this project is in beta stage, it's natural for upgrades to maybe break an existing version so just to keep it safe, a tagged version would be much appreciated.

Thanks!

**Comment by lmangani** [comment]
Thanks @mr-karan - good point indeed.  Since we are currently pushing features/fixes intensively and we pretty much need all users on the latest version and support validation, we're intentionally sticking with `latest` tag but once the release cycle will switch to stable feature releases we'll modify the GitHub action to push tagged containers.

Let's keep this issue open as a gateway reminder towards this step.

Thanks!

**Comment by lmangani** [comment]
_TODO:_ change [docker tag](https://github.com/lmangani/cLoki/blob/master/.github/workflows/bump_version.yml#L86) to `${{ steps.version-bump.outputs.newTag }}`

**Comment by derlaft** [comment]
@lmangani there's already "v2" released with some breaking changes - is it finally time to enable docker tags?

**Comment by lmangani** [comment]
@derlaft yes and good news, we've been testing this on a separate staging and it'll soon be merged into the actions
